const esbuild = require('esbuild');
const fs = require('fs');
const path = require('path');

// Read config values from build-config.ts (generated by generate-build-config.cjs)
const buildConfigPath = path.join(__dirname, 'app', 'lib', 'build-config.ts');
const buildConfigContent = fs.readFileSync(buildConfigPath, 'utf8');
const stackName = buildConfigContent.match(/STACK_PREFIX:\s*'([^']+)'/)?.[1] || '';
const region = buildConfigContent.match(/AWS_REGION:\s*'([^']+)'/)?.[1] || 'us-west-2';

if (!stackName) {
    console.error('❌ ERROR: stackName is empty! Run generate-build-config.cjs first.');
    process.exit(1);
}

console.log('📋 Building Lambda handlers with:');
console.log('   STACK_PREFIX:', stackName);
console.log('   AWS_REGION:', region);
console.log('');

// Common build configuration
const commonConfig = {
    bundle: true,
    platform: 'node',
    target: 'node20',
    external: ['@aws-sdk/*'], // Exclude AWS SDK as it's available in Lambda runtime
    sourcemap: true,
    format: 'cjs', // Ensure CommonJS format for Lambda
    packages: 'bundle',
    define: {
        'process.env.NODE_ENV': '"production"',
        // Inject config values at build time
        'process.env.STACK_PREFIX': `"${stackName}"`,
        'process.env.AWS_REGION': `"${region}"`,
    },
    conditions: ['node'],
    mainFields: ['main', 'module'],
};

async function buildLambdaHandlers() {
    try {
        console.log('🏗️  Building main server handler...');
        await esbuild.build({
            ...commonConfig,
            entryPoints: ['server.ts'],
            outfile: 'build/lambda/index.cjs',
        });
        console.log('✅ Main server handler built successfully');
        console.log('   Output: build/lambda/index.cjs');
        console.log('');

        console.log('🏗️  Building streaming handler...');
        await esbuild.build({
            ...commonConfig,
            entryPoints: ['streaming.ts'],
            outfile: 'build/lambda/streaming.cjs',
        });
        console.log('✅ Streaming handler built successfully');
        console.log('   Output: build/lambda/streaming.cjs');
        console.log('');

        console.log('Building JWT authorizer...');
        await esbuild.build({
            ...commonConfig,
            entryPoints: ['lambda-authorizer/index.ts'],
            outfile: 'build/lambda-authorizer/index.cjs',
        });
        console.log('JWT authorizer built successfully');
        console.log('   Output: build/lambda-authorizer/index.cjs');
        console.log('');

        console.log('🎉 All Lambda handlers built successfully!');
        console.log('   STACK_PREFIX injected as:', stackName);
        console.log('   AWS_REGION injected as:', region);

    } catch (error) {
        console.error('❌ Build failed:', error);
        process.exit(1);
    }
}

buildLambdaHandlers();
